# Generated by Django 4.2.1 on 2023-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(default=24, max_length=111),
            preserve_default=False,
        ),
    ]
